package org.example.authenticationservice.dtos;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ValidateTokenRequestDto {
    private Long userId;
    private String token;
    // same random token can be generated by multiple user
    // JWT token is unique for each user
    // but randomly generated token can be same for multiple user
    // in reality we don't need userId

}
